language: node_js
node_js:
  - "6.9.1"
sudo: required
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run test &&
    bash ./go.sh build
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    all_branches: true
after_success: npm run codecov
