language: node_js
node_js:
  - "6.9.1"
services:
  - docker
cache: yarn
script:
  - npm run test &&
    bash ./go.sh build
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    all_branches: true
