language: node_js
node_js:
  - "6.3.1"
branches:
  only:
  - master
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - bash scripts/go.sh copy &&
    bash scripts/go.sh build fetch &&
    bash scripts/go.sh build server &&
    bash scripts/go.sh push fetch &&
    bash scripts/go.sh push server
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy/deploy.sh
