language: node_js
node_js:
  - "7.9.0"
sudo: required
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./go.sh build && bash ./scripts/deploy.sh
  on:
    all_branches: true
after_success: npm run codecov
